let nombreDelCurso = "React Native";
let profesor = "Nicolas Isnardi";
let duracionEnMeses = 3;
let virtual = true;
let finalizado = false;
let cupos = undefined;
let opinionesNegativas = null;
console.log("nombreDelCurso: ", nombreDelCurso);
console.log("profesor: ", profesor);
console.log("duracionEnMeses: ", duracionEnMeses);
console.log("virtual: ", virtual);
console.log("finalizado: ", finalizado);
console.log("cupos: ", cupos);
console.log("opinionesNegativas: ", opinionesNegativas);
console.log("nombreDelCurso: ", typeof nombreDelCurso);
console.log("profesor: ", typeof profesor);
console.log("duracionEnMeses: ", typeof duracionEnMeses);
console.log("virtual: ", typeof virtual);
console.log("finalizado: ", typeof finalizado);
console.log("cupos: ", typeof cupos);
console.log("opinionesNegativas: ", typeof opinionesNegativas);
