const numero = 9;
console.log(`Tabla del ${numero}`);
console.log(`1 x ${numero} = ${1 * numero}`);
console.log(`2 x ${numero} = ${2 * numero}`);
console.log(`3 x ${numero} = ${3 * numero}`);
console.log(`4 x ${numero} = ${4 * numero}`);
console.log(`5 x ${numero} = ${5 * numero}`);
console.log(`6 x ${numero} = ${6 * numero}`);
console.log(`7 x ${numero} = ${7 * numero}`);
console.log(`8 x ${numero} = ${8 * numero}`);
console.log(`9 x ${numero} = ${9 * numero}`);
console.log(`10 x ${numero} = ${10 * numero}`);
